#version: '3.9'

services:
  api:
    build: .
    ports:
      - "1000:1000"
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgres://postgres:1020@db:5432/Ejemplo?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1020
      POSTGRES_DB: Ejemplo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Asegúrate de que el puerto 443 también esté expuesto
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/certbot  # Esta carpeta es usada por Certbot
      - ./etc/letsencrypt:/etc/letsencrypt  # Almacenará los certificados de Certbot
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./html:/var/www/certbot
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot -d app1.between-bytes.tech -d app2.between-bytes.tech --email tu_correo@example.com --agree-tos --non-interactive
    depends_on:
      - nginx

volumes:
  pgdata:

